-- ============================================================
-- 温泉小镇导览 · PostgreSQL schema
-- 设计要点：
--  1) 地点(place)与设施(facility)分层：维护挂在设施/子设施上，
--     某泡池检修不会让同馆餐饮/住宿消失；推荐展开到设施级。
--  2) 泉质(spring_quality)带来源(source_record)，仅描述，不做医疗功效推断。
--  3) 开放时间按周几(day_of_week) + 跨日标记(crosses_midnight)建模，
--     维护支持跨日；判定时间窗时二者统一求交集。
--  4) 步行段缓存(segment_cache)带 TTL/OSRM 版本，支撑全量重算 vs 局部修复一致性。
--  5) 行程点带 manual_lock，锁定后开放时间变化只报冲突，绝不偷偷换点。
--  6) 编辑版本(version/device_id/base_version)支撑两个设备并发编辑与冲突检测。
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------- 来源记录 ----------
CREATE TABLE source_record (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind         TEXT NOT NULL CHECK (kind IN ('official','operator','field_survey','user_report','import')),
  url          TEXT,
  title        TEXT,
  retrieved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  trust_level  SMALLINT NOT NULL DEFAULT 2 CHECK (trust_level BETWEEN 1 AND 5),
  status       TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','stale','dead','unverified')),
  note         TEXT
);

-- 链接健康巡检（链接失效验收）
CREATE TABLE link_check (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id   BIGINT NOT NULL REFERENCES source_record(id) ON DELETE CASCADE,
  checked_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  http_status INT,
  ok          BOOLEAN NOT NULL,
  detail      TEXT
);
CREATE INDEX idx_link_check_source ON link_check(source_id, checked_at DESC);

-- ---------- 地点（场馆/店铺） ----------
CREATE TABLE place (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('bathhouse','lodging','restaurant','cafe','shop','park','station','other')),
  lat         DOUBLE PRECISION NOT NULL,
  lng         DOUBLE PRECISION NOT NULL,
  address     TEXT,
  -- 待核信息：信息不完整/来源过期时为 true，前端明确展示“待核”
  needs_verification BOOLEAN NOT NULL DEFAULT FALSE,
  verification_note  TEXT,
  merged_into BIGINT REFERENCES place(id),   -- 地点合并：旧地点指向保留地点
  active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_place_kind ON place(kind) WHERE active AND merged_into IS NULL;
CREATE INDEX idx_place_name_trgm ON place USING gin (name gin_trgm_ops);

CREATE TABLE place_alias (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
  alias    TEXT NOT NULL,
  UNIQUE (alias)
);

-- ---------- 设施（场馆内可单独推荐/检修的单元） ----------
-- kind: pool 泡池 / bath_area 浴区 / restaurant_floor 餐饮楼层 /
--       guest_room 客房 / play_room 亲子游乐 / nursing_room 母婴室 / parking 停车场 ...
CREATE TABLE facility (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id    BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
  parent_id   BIGINT REFERENCES facility(id),      -- 子泡池挂在浴区下
  name        TEXT NOT NULL,
  kind        TEXT NOT NULL,
  family_friendly BOOLEAN NOT NULL DEFAULT FALSE, -- 亲子设施
  -- 针对住宿/餐饮/设施本身的属性标记（地图筛选用）
  is_stay     BOOLEAN NOT NULL DEFAULT FALSE,
  is_food     BOOLEAN NOT NULL DEFAULT FALSE,
  walk_min_from_entrance INT NOT NULL DEFAULT 0,  -- 从场馆入口进入后的额外步行分钟
  default_duration_s     INT NOT NULL DEFAULT 3600, -- 行程组合时该设施默认停留时长
  active      BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_facility_place ON facility(place_id);
CREATE INDEX idx_facility_parent ON facility(parent_id);

-- ---------- 泉质（有来源的描述信息，不作医疗功效推断） ----------
CREATE TABLE spring_quality (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id     BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
  source_id    BIGINT NOT NULL REFERENCES source_record(id),
  spring_name  TEXT,
  quality_type TEXT,                 -- 如：単純温泉 / ナトリウム-塩化物泉
  temperature_c NUMERIC(4,1),
  ph           NUMERIC(3,2),
  description  TEXT NOT NULL,       -- 仅描述性文本
  observed_at  DATE,
  CHECK (description !~* '(治る|治療|効能|疗效|治愈|治疗|医疗功效)')
);
COMMENT ON TABLE spring_quality IS '泉质仅为带来源的描述信息；禁止录入医疗功效断言';

-- ---------- 开放时间（周循环，支持跨日） ----------
CREATE TABLE opening_hours (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_id      BIGINT NOT NULL REFERENCES facility(id) ON DELETE CASCADE,
  day_of_week      SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6), -- 0=周日
  open_time        TIME NOT NULL,
  close_time       TIME NOT NULL,
  crosses_midnight BOOLEAN NOT NULL DEFAULT FALSE,  -- close 属次日
  effective_from   DATE NOT NULL DEFAULT CURRENT_DATE,
  effective_to     DATE,
  source_id        BIGINT REFERENCES source_record(id),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_oh_facility ON opening_hours(facility_id);

-- ---------- 维护（可挂设施或子设施，支持跨日） ----------
CREATE TABLE maintenance (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_id  BIGINT NOT NULL REFERENCES facility(id) ON DELETE CASCADE,
  title        TEXT NOT NULL,
  start_at     TIMESTAMPTZ NOT NULL,
  end_at       TIMESTAMPTZ NOT NULL,
  reason       TEXT,
  source_id    BIGINT REFERENCES source_record(id),
  CHECK (end_at > start_at)
);
CREATE INDEX idx_maint_facility_time ON maintenance(facility_id, start_at, end_at);

-- ---------- 步行距离/耗时（以实测/来源为准，可被 OSRM 覆盖） ----------
CREATE TABLE walking_edge (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_place  BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
  to_place    BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
  distance_m  INT,
  duration_s  INT,
  source_id   BIGINT REFERENCES source_record(id),
  measured_at DATE,
  UNIQUE (from_place, to_place),
  CHECK (from_place <> to_place)
);

-- 路段耗时缓存：全量重算/局部修复共用，保证同一路段只有一个答案
CREATE TABLE segment_cache (
  cache_key     TEXT PRIMARY KEY,           -- `${from}:${to}:${mode}:${osrmVersion}`
  from_place    BIGINT NOT NULL,
  to_place      BIGINT NOT NULL,
  duration_s    INT NOT NULL,
  distance_m    INT NOT NULL,
  source        TEXT NOT NULL,              -- haversine | measured | osrm
  computed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at    TIMESTAMPTZ NOT NULL,
  invalid       BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_segment_exp ON segment_cache(expires_at);

-- ---------- 主题行程 ----------
CREATE TABLE itinerary (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT,
  theme       TEXT,
  version     INT NOT NULL DEFAULT 1,       -- 乐观锁版本
  device_id   TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE itinerary_item (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itinerary_id  BIGINT NOT NULL REFERENCES itinerary(id) ON DELETE CASCADE,
  position      INT NOT NULL,
  place_id      BIGINT NOT NULL REFERENCES place(id),
  facility_id   BIGINT REFERENCES facility(id),  -- 展开到“真正要去的设施”
  arrive_at     TIMESTAMPTZ,
  depart_at     TIMESTAMPTZ,
  manual_lock   BOOLEAN NOT NULL DEFAULT FALSE,  -- 手工锁定
  lock_note     TEXT,
  -- 锁定时刻的时间窗快照；开放时间变化后用来解释冲突
  locked_window JSONB,
  CONSTRAINT chk_order CHECK (depart_at IS NULL OR arrive_at IS NULL OR depart_at >= arrive_at)
);
CREATE INDEX idx_item_itinerary ON itinerary_item(itinerary_id, position);

-- 行程重算审计：记录每次完整重算/局部修复，便于比对一致性
CREATE TABLE itinerary_recompute_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itinerary_id BIGINT NOT NULL REFERENCES itinerary(id) ON DELETE CASCADE,
  mode         TEXT NOT NULL CHECK (mode IN ('full','partial')),
  changed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  changed_items JSONB NOT NULL,
  conflicts    JSONB NOT NULL DEFAULT '[]',
  cache_fresh  JSONB NOT NULL DEFAULT '{}'
);

-- ---------- 离线包（过期离线包验收） ----------
CREATE TABLE offline_package (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version     TEXT NOT NULL,
  published_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at  TIMESTAMPTZ NOT NULL,
  manifest    JSONB NOT NULL DEFAULT '{}',
  active      BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---------- 双设备编辑（离线/并发） ----------
CREATE TABLE itinerary_edit (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itinerary_id BIGINT NOT NULL REFERENCES itinerary(id) ON DELETE CASCADE,
  device_id    TEXT NOT NULL,
  base_version INT NOT NULL,
  op           JSONB NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  applied      BOOLEAN NOT NULL DEFAULT FALSE,
  conflict     BOOLEAN NOT NULL DEFAULT FALSE,
  detail       TEXT
);
CREATE INDEX idx_edit_itinerary ON itinerary_edit(itinerary_id, created_at);
